/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2015-09-22 12:35:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class fileUploadFloor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <title>Triangle</title>\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/css/fileUploadFloor.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<div class=\"floorLabelBox\">\n");
      out.write("\t\t<span>3F</span>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"wrapper\">\n");
      out.write("\t\t<div class=\"contentsArea ani\">\n");
      out.write("   \t\t \t<div class=\"titleBox\">\n");
      out.write("   \t\t \t\tPlease select an image to be triangulation.\n");
      out.write("   \t\t \t</div>\n");
      out.write("\t\t\t<div class=\"fieldBox\"> \n");
      out.write("\t   \t\t \t<div id=\"dropzone\">\n");
      out.write("\t  \t\t\t\t<div class=\"text ani\">File Select <br> Drag&amp;Drop</div>\n");
      out.write("\t  \t\t\t\t<input id=\"fileSelect\" type=\"file\" accept=\"image/png, application/pdf\" />\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"fieldBox\">\n");
      out.write("\t\t\t\t<div class=\"captureBox\">\n");
      out.write("\t\t\t\t\t<button class=\"button webcam ani\">WebCam<br>Capture</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"titleBox down\">\n");
      out.write("   \t\t \t\tUpload your portrait file. You can get better results. This service is equipped with a face recognition system.\n");
      out.write("   \t\t \t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"canvasBox\">\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<canvas id=\"previewCanvas\">\n");
      out.write("   \t\t \t\t</canvas> \n");
      out.write("   \t\t \t</div>\n");
      out.write("   \t\t \t<div>\n");
      out.write("\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t<button class=\"nbutton upload\">upload</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t<button class=\"nbutton cancel\">cancel</button>\n");
      out.write("\t\t\t\t</div> \n");
      out.write("   \t\t \t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t   \n");
      out.write("    <!-- ScriptArea -->\n");
      out.write("\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.11.3.min.js\"></script>\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-migrate-1.2.1.min.js\"></script>\n");
      out.write("\n");
      out.write("    <script type=\"text/javascript\" src=\"/js/delaunay.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"/js/fileUploadFloor.js\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
